version: "3.8"

services:
  web:
    container_name: oauth2-app
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: python OauthApp/manage.py runserver localhost:8000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres