# Generated by Django 3.1.1 on 2020-12-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='null@email.com', max_length=360, unique=True)),
                ('access_token', models.CharField(default='', max_length=360)),
                ('refresh_token', models.CharField(default='', max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='null@email.com', max_length=360, unique=True)),
                ('access_token', models.CharField(default='', max_length=360)),
                ('refresh_token', models.CharField(default='', max_length=360)),
                ('token_uri', models.CharField(default='', max_length=526)),
            ],
        ),
    ]
