# Generated by Django 3.1.1 on 2020-12-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('access_token', models.CharField(default='', max_length=360)),
                ('refresh_token', models.CharField(default='', max_length=360)),
            ],
        ),
    ]
