# Generated by Django 3.1.1 on 2020-12-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth2', '0002_youtubeauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeauth',
            name='token_uri',
            field=models.CharField(default='', max_length=526),
        ),
    ]
